title: "DSCI 310: Historical Horse Population in Canada"
author: "Tiffany Timbers & Jordan Bourak"
date: "2021-11-22"

execute:
  execute_notebooks: force 

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

  
# In _config.yml
sphinx:
  config:
    bibtex_reference_style: author_year

only_build_toc_files: true